import { Modpack } from "./modpack";

export const MODPACKS: Modpack[] = [
    {name:'Medieval World',
    type:'Forge',
    version:'1.19.4',
    date:'Just Rius 03.05.23',
    img:'assets/img/modpacks/modpack1.png',
    description:'Крутая рпг сборка которая переместит вас куда нибудь без разницы это просто тестовый текст не несущий серьезной информации',
    themeClass_1:'vanilla',
    theme_1:'Ванила',
    themeClass_2:'fantasy',
    theme_2:'Фентези',
    views: 28372 },
    {name:'Fantasy Craft',
    type:'Fabric',
    version:'1.16.5',
    date:'Saudade Studio 01.04.23',
    img:'assets/img/modpacks/modpack2.png',
    description:'Вообще отпадная сборка, в которой ничего нет, как и самой сборки, господи, как же мне не хватает lorem ipsum здесь, кто бы знал как это нудно заполнять всякой фгней которую сам на ходу придумываешь',
    themeClass_1:'vanilla',
    theme_1:'Ванила',
    themeClass_2:'industrial',
    theme_2:'Индустриальная',
    views: 114821 },
    {name:'Medieval World',
    type:'Fabric',
    version:'1.19.4',
    date:'Just Rius 03.05.23',
    img:'assets/img/modpacks/modpack1.png',
    description:'Крутая рпг сборка которая переместит вас куда нибудь без разницы это просто тестовый текст не несущий серьезной информации',
    themeClass_1:'industrial',
    theme_1:'Индустриальная',
    views: 28372 },
    {name:'Something else craft',
    type:'Fabric',
    version:'1.12.2',
    date:'Saudade Studio 01.04.23',
    img:'assets/img/modpacks/modpack2.png',
    description:'Вообще отпадная сборка, в которой ничего нет, как и самой сборки, господи, как же мне не хватает lorem ipsum здесь, кто бы знал как это нудно заполнять всякой фгней которую сам на ходу придумываешь',
    themeClass_1:'vanilla',
    theme_1:'Ванила',
    themeClass_2:'industrial',
    theme_2:'Индустриальная',
    views: 114821 },
    {name:'Medieval World',
    type:'Fabric',
    version:'1.19.4',
    date:'Just Rius 03.05.23',
    img:'assets/img/modpacks/modpack1.png',
    description:'Крутая рпг сборка которая переместит вас куда нибудь без разницы это просто тестовый текст не несущий серьезной информации',
    themeClass_1:'vanilla',
    theme_1:'Ванила',
    themeClass_2:'fantasy',
    theme_2:'Фентези',
    views: 28372 },
    {name:'Medieval World',
    type:'Fabric',
    version:'1.16.5',
    date:'Saudade Studio 01.04.23',
    img:'assets/img/modpacks/modpack2.png',
    description:'Вообще отпадная сборка, в которой ничего нет, как и самой сборки, господи, как же мне не хватает lorem ipsum здесь, кто бы знал как это нудно заполнять всякой фгней которую сам на ходу придумываешь',
    themeClass_1:'vanilla',
    theme_1:'Ванила',
    views: 114821 },
    {name:'Medieval World',
    type:'Forge',
    version:'1.8.1',
    date:'Just Rius 01.02.22',
    img:'assets/img/modpacks/modpack1.png',
    description:'Крутая рпг сборка которая переместит вас куда нибудь без разницы это просто тестовый текст не несущий серьезной информации',
    themeClass_1:'vanilla',
    theme_1:'Ванила',
    themeClass_2:'fantasy',
    theme_2:'Фентези',
    views: 28372 },
    {name:'Medieval World',
    type:'Forge',
    version:'1.19.4',
    date:'Just Rius 03.05.23',
    img:'assets/img/modpacks/modpack1.png',
    description:'Крутая рпг сборка которая переместит вас куда нибудь без разницы это просто тестовый текст не несущий серьезной информации',
    themeClass_1:'vanilla',
    theme_1:'Ванила',
    themeClass_2:'fantasy',
    theme_2:'Фентези',
    views: 28372 }
]